In [126]:
import pandas as pd
import geopandas
import shapely.wkt
import json

In [30]:
def _gdf_to_dict(gdf):
    # get name of the geometry column
    name = gdf.geometry.name
    
    copy = gdf.copy()
    # convert it to wkt
    copy[name] = copy.geometry.apply(lambda x: shapely.wkt.dumps(x))

    return _df_to_dict(copy)

In [35]:
def _df_to_dict(df):
    ''' Create an input dict for Kepler.gl using a DataFrame object

    Inputs:
    - df: a DataFrame object

    Returns:
    - dictionary: a dictionary variable that can be used in Kepler.gl

    '''
    return df.to_dict('split')

In [56]:
df = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela'],
     'Latitude': [-34.58, -15.78, -33.45, 4.60, 10.48],
     'Longitude': [-58.66, -47.91, -70.66, -74.08, -66.86]})

df2 = pd.DataFrame(
    {'City': ['Buenos Aires', 'Brasilia', 'Santiago', 'Bogota', 'Caracas'],
     'Country': ['Argentina', 'Brazil', 'Chile', 'Colombia', 'Venezuela']})

In [62]:
# gdf = geopandas.GeoDataFrame(df, geometry=geopandas.points_from_xy(df.Longitude, df.Latitude))
# gdf.rename(index=str, columns={"geometry": "point"})
# display(gdf)
# gdf = geopandas.GeoDataFrame(df)
gdf2 = geopandas.GeoDataFrame(df2)
display(gdf2)
print (gdf2.geometry.name)

           City    Country
0  Buenos Aires  Argentina
1      Brasilia     Brazil
2      Santiago      Chile
3        Bogota   Colombia
4       Caracas  Venezuela

AttributeError: No geometry data set yet (expected in column 'geometry'.

In [38]:
print(gdf.head())
print(isinstance(gdf, geopandas.GeoDataFrame))
print(isinstance(df, geopandas.GeoDataFrame))

           City    Country  Latitude  Longitude               geometry
0  Buenos Aires  Argentina    -34.58     -58.66  POINT (-58.66 -34.58)
1      Brasilia     Brazil    -15.78     -47.91  POINT (-47.91 -15.78)
2      Santiago      Chile    -33.45     -70.66  POINT (-70.66 -33.45)
3        Bogota   Colombia      4.60     -74.08     POINT (-74.08 4.6)
4       Caracas  Venezuela     10.48     -66.86   POINT (-66.86 10.48)
True
False

In [50]:
# gdf1 = _gdf_to_dict(gdf)
# display(gdf1)
print(isinstance(gdf2, geopandas.GeoDataFrame))

# display(gdf2)
_gdf_to_dict(gdf2)

True

AttributeError: No geometry data set yet (expected in column 'geometry'.

In [22]:
# get name of the geometry column
name = gdf.geometry.name
# convert it to wkt
gdf[name] = gdf.geometry.apply(lambda x: shapely.wkt.dumps(x))

In [23]:
display(gdf)

,City,Country,Latitude,Longitude,geometry
0,Buenos Aires,Argentina,-34.58,-58.66,POINT (-58.6599999999999966 -34.5799999999999983)
1,Brasilia,Brazil,-15.78,-47.91,POINT (-47.9099999999999966 -15.7799999999999994)
2,Santiago,Chile,-33.45,-70.66,POINT (-70.6599999999999966 -33.4500000000000028)
3,Bogota,Colombia,4.60,-74.08,POINT (-74.0799999999999983 4.5999999999999996)
4,Caracas,Venezuela,10.48,-66.86,POINT (-66.8599999999999994 10.4800000000000004)

In [24]:
gdf.to_dict('split')

{'columns': ['City', 'Country', 'Latitude', 'Longitude', 'geometry'],
 'data': [['Buenos Aires',
   'Argentina',
   -34.58,
   -58.66,
   'POINT (-58.6599999999999966 -34.5799999999999983)'],
  ['Brasilia',
   'Brazil',
   -15.78,
   -47.91,
   'POINT (-47.9099999999999966 -15.7799999999999994)'],
  ['Santiago',
   'Chile',
   -33.45,
   -70.66,
   'POINT (-70.6599999999999966 -33.4500000000000028)'],
  ['Bogota',
   'Colombia',
   4.6,
   -74.08,
   'POINT (-74.0799999999999983 4.5999999999999996)'],
  ['Caracas',
   'Venezuela',
   10.48,
   -66.86,
   'POINT (-66.8599999999999994 10.4800000000000004)']],
 'index': [0, 1, 2, 3, 4]}

In [63]:
url = "http://d2ad6b4ur7yvpq.cloudfront.net/naturalearth-3.3.0/ne_110m_land.geojson"
country_gdf = geopandas.read_file(url)
display(country_gdf)

     scalerank featureclass                                           geometry
0            1      Country  POLYGON ((-59.57209469261153 -80.0401787250963...
1            1      Country  POLYGON ((-159.2081835601977 -79.4970594217087...
2            1      Country  POLYGON ((-45.15475765642103 -78.0470696005867...
3            1      Country  POLYGON ((-121.2115113938571 -73.5009904990060...
4            1      Country  POLYGON ((-125.5595664068953 -73.4813534547352...
5            1      Country  POLYGON ((-98.98154964882391 -71.9333342489997...
6            1      Country  POLYGON ((-68.45134599473033 -70.9558228557667...
7            1      Country  POLYGON ((-58.61414282900103 -64.1524671301332...
8            1      Country  POLYGON ((-67.75 -53.85, -66.45 -54.45, -65.05...
9            1      Country  POLYGON ((-58.55 -51.1, -57.75 -51.55, -58.05 ...
10           1      Country  POLYGON ((70.28 -49.71, 68.745 -49.775, 68.72 ...
11           1      Country  POLYGON ((145.3979781434949 -40.79254851660599...
12           1      Country  POLYGON ((173.0203747907408 -40.91905242285642...
13           1      Country  POLYGON ((174.6120089053306 -36.15639739354056...
14           1      Country  POLYGON ((167.1200114280869 -22.15999073658352...
15           1      Country  POLYGON ((178.3736000000002 -17.33992, 178.718...
16           1      Country  POLYGON ((179.3641426619643 -16.80135407694685...
17           1      Country  POLYGON ((-179.9173693847653 -16.5017831356493...
18           1      Country  POLYGON ((167.8448767438451 -16.46633310309716...
19           1      Country  POLYGON ((167.1077124372015 -14.93392017991395...
20           1      Country  POLYGON ((50.05651085795725 -13.55576140712201...
21           1      Country  POLYGON ((143.5618111513 -13.76365569423221, 1...
22           1      Country  POLYGON ((162.1190246930409 -10.48271900802114...
23           1      Country  POLYGON ((120.7156087586305 -10.23958139408788...
24           1      Country  POLYGON ((160.852228631838 -9.872937106977105,...
25           1      Country  POLYGON ((161.6799817242891 -9.599982191611375...
26           1      Country  POLYGON ((124.4359501486194 -10.14000090906144...
27           1      Country  POLYGON ((117.9000183452078 -8.095681247594925...
28           1      Country  POLYGON ((122.9035372254361 -8.094234307490751...
29           1      Country  POLYGON ((159.8750272971986 -8.337320244991716...
..         ...          ...                                                ...
97           1      Country  POLYGON ((-104.5 73.42, -105.38 72.76000000000...
98           1      Country  POLYGON ((-76.34 73.10268498995302, -76.251403...
99           1      Country  POLYGON ((-86.56217851433405 73.15744700793854...
100          1      Country  POLYGON ((-100.35642 73.84389, -99.16387 73.63...
101          1      Country  POLYGON ((143.60385 73.21244, 142.08763 73.205...
102          1      Country  POLYGON ((-93.19629553910013 72.77199249947327...
103          1      Country  POLYGON ((-120.46 71.40000000000001, -123.0921...
104          1      Country  POLYGON ((150.73167 75.08405999999999, 149.575...
105          1      Country  POLYGON ((-93.61275590694041 74.97999726022442...
106          1      Country  POLYGON ((145.086285 75.56262, 144.3 74.819999...
107          1      Country  POLYGON ((-98.5 76.72, -97.735585 76.256560000...
108          1      Country  POLYGON ((-108.21141 76.20168, -107.8194299999...
109          1      Country  POLYGON ((57.5356925799924 70.72046397570224, ...
110          1      Country  POLYGON ((-94.68408586299947 77.09787832305838...
111          1      Country  POLYGON ((-116.1985865955074 77.64528677032621...
112          1      Country  POLYGON ((106.9702758789063 76.97430419921875,...
113          1      Country  POLYGON ((-93.84000301794401 77.5199972602345,...
114          1      Country  POLYGON ((-110.1869380359131 77.69701487905039...
115          1      Country  POLYGON ((24.72412 77.85384999999999, 22.49032...
116          1      Country  POLYGON ((-109.6631457182026 78.60197256134569...
117          1      Country  POLYGON ((-95.83029496944926 78.05694122996334...
118          1      Country  POLYGON ((-100.0601918200522 78.32475434031582...
119          1      Country  POLYGON ((105.07547 78.30689, 99.43814 77.9210...
120          1      Country  POLYGON ((18.25183 79.70175, 21.54383 78.95611...
121          1      Country  POLYGON ((25.44762535981198 80.40734039989459,...
122          1      Country  POLYGON ((51.13618655783139 80.54728017854103,...
123          1      Country  POLYGON ((99.93976000000001 78.88094, 97.75794...
124          1      Country  POLYGON ((-87.02 79.66, -85.81435 79.3369, -87...
125          1      Country  POLYGON ((-68.5 83.10632151676583, -65.82735 8...
126          1      Country  POLYGON ((-27.10046 83.51966, -20.84539 82.726...

[127 rows x 3 columns]

In [66]:
df = pd.read_csv('hex-data.csv')

In [67]:
# assign config = hex_config
%run hex_config.py

In [121]:
import keplergl_jupyter as keplergl
map_1 = keplergl.KeplerGl(height=500)
map_1

Documentation: https://github.com/keplergl/kepler.gl/blob/master/docs/keplergl-jupyter/user-guide.md

KeplerGl(height=500)

In [110]:
df_with_geometry = pd.DataFrame(
    {'id': [1, 2],
     'geojson_string': [
       '{"type":"Polygon", "coordinates":[[[-74.158491,40.835947],[-74.157914,40.83902],[-74.148473,40.834522],[-74.146471,40.836645],[-74.142598,40.833128],[-74.140177,40.832492],[-74.136732,40.836791],[-74.142706,40.840604],[-74.144667,40.84312],[-74.142936,40.844974],[-74.136054,40.84119],[-74.1356,40.841703],[-74.133665,40.840712],[-74.133028,40.841321],[-74.13274,40.839586],[-74.121853,40.834098],[-74.121087,40.831],[-74.124447,40.822169],[-74.130031,40.819962],[-74.149242,40.830537],[-74.148818,40.830916],[-74.150888,40.833143],[-74.151923,40.832074],[-74.158491,40.835947]]]}',
       '{"type":"Polygon", "coordinates":[[[-74.387589,40.632238],[-74.401749,40.640393],[-74.386745,40.653316],[-74.374682,40.646553],[-74.372634,40.6468],[-74.371828,40.644885],[-74.374122,40.642352],[-74.37327,40.641829],[-74.375777,40.636295],[-74.37717,40.634842],[-74.382333,40.632417],[-74.384457,40.630453],[-74.387589,40.632238]]]}'          
     ]
})
display(df_with_geometry)

                                      geojson_string  id
0  {"type":"Polygon", "coordinates":[[[-74.158491...   1
1  {"type":"Polygon", "coordinates":[[[-74.387589...   2

In [112]:
df_w_wkt = pd.DataFrame(
    {'id': [1, 2],
     'geojson_string': [
         "POLYGON ((-74.158491 40.835947, -74.130031 40.819962, -74.149242 40.830537, -74.148818 40.830916, -74.150888 40.833143, -74.151923 40.832074, -74.158491 40.835947))",
         "POLYGON ((-74.387589 40.632238, -74.375777 40.636295, -74.37717 40.634842, -74.382333 40.632417, -74.384457 40.630453, -74.387589 40.632238))"
     ]
})

In [133]:
geometryString = {
    'type': 'Polygon',
    'coordinates': [[[-74.158491,40.835947],[-74.148473,40.834522],[-74.142598,40.833128],[-74.151923,40.832074],[-74.158491,40.835947]]]
}
json_str = json.dumps(geometryString)
print 

df_with_geometry = pd.DataFrame({
    'id': [1, 2], 'geojson_string': [json_str, json_str]
})
display(df_with_geometry)

                                      geojson_string  id
0  {"type": "Polygon", "coordinates": [[[-74.1584...   1
1  {"type": "Polygon", "coordinates": [[[-74.1584...   2

In [134]:
map_1.add_data(df_with_geometry, "df_with_geometry_3")

In [114]:
map_1.add_data(df_w_wkt, "df_w_wkt")

In [88]:
map_1.data

{'df_with_geometry': {'columns': ['geojson_string', 'id'],
  'data': [['{type:Polygon,coordinates:[[[-74.158491,40.835947],[-74.157914,40.83902],[-74.148473,40.834522],[-74.146471,40.836645],[-74.142598,40.833128],[-74.140177,40.832492],[-74.136732,40.836791],[-74.142706,40.840604],[-74.144667,40.84312],[-74.142936,40.844974],[-74.136054,40.84119],[-74.1356,40.841703],[-74.133665,40.840712],[-74.133028,40.841321],[-74.13274,40.839586],[-74.121853,40.834098],[-74.121087,40.831],[-74.124447,40.822169],[-74.130031,40.819962],[-74.149242,40.830537],[-74.148818,40.830916],[-74.150888,40.833143],[-74.151923,40.832074],[-74.158491,40.835947]]]}',
    1],
   ['{type:Polygon,coordinates:[[[-74.387589,40.632238],[-74.401749,40.640393],[-74.386745,40.653316],[-74.374682,40.646553],[-74.372634,40.6468],[-74.371828,40.644885],[-74.374122,40.642352],[-74.37327,40.641829],[-74.375777,40.636295],[-74.37717,40.634842],[-74.382333,40.632417],[-74.384457,40.630453],[-74.387589,40.632238]]]}',
    2]],
  'index': [0, 1]}}